name: CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    uses: yavorfingarov/Workflows/.github/workflows/build.yml@master
    with:
      unit-tests-path: ./tests/SimpleRequestLogger.UnitTests
      status-gist-id: ee725e01afca4342ff8ea785553d05d2
    secrets: inherit

  publish:
    name: Publish
    needs: build
    if: ${{ needs.build.outputs.run-next == 'true' }}
    uses: yavorfingarov/Workflows/.github/workflows/publish-nuget.yml@master
    with:
      csproj-path: ./src/SimpleRequestLogger/SimpleRequestLogger.csproj
    secrets: inherit
